<?php

namespace App\Models\Messages\Ledger;

use App\Exceptions\Breaker;
use App\Models\LedgerAccount;
use App\Models\Messages\Message;

class Name extends Message
{
    public string $language;
    public string $name;
    public string $ownerUuid;
    public ?string $revision;

    /**
     * @inheritdoc
     */
    public static function fromRequest(array $data, int $opFlag): self
    {
        $name = new static();
        if (isset($data['name'])) {
            $name->name = $data['name'];
        }
        if (isset($data['language'])) {
            $name->language = $data['language'];
        }
        if ($opFlag & self::FN_VALIDATE) {
            $name->validate($opFlag);
        }

        return $name;
    }

    /**
     * Populate an array of names with request data.
     *
     * @param array $data Data generated by the request.
     * @param int $opFlag Bitmask of the request operation (may include FM_VALIDATE)
     * @param int $minimum the minimum number of elements that should be present.
     * @return Name[]
     * @throws Breaker
     */
    public static function fromRequestList(array $data, int $opFlag, int $minimum = 0): array
    {
        $names = [];
        foreach ($data as $nameData) {
            $message = self::fromRequest($nameData, $opFlag);
            $names[$message->language] = $message;
        }
        if (count($names) < $minimum) {
            $entry = $minimum === 1 ? 'entry' : 'entries';
            throw Breaker::withCode(
                Breaker::BAD_REQUEST, ["must provide at least $minimum name $entry"]
            );
        }

        return $names;
    }

    /**
     * @inheritdoc
     */
    public function validate(int $opFlag): self
    {
        if (!isset($this->name)) {
            throw Breaker::withCode(
                Breaker::BAD_REQUEST, [__("must include name property")]
            );
        }
        $this->language ??= LedgerAccount::rules()->language->default;

        return $this;
    }
}
